elasticsearch:
  image: elasticsearch
  volumes:
    - ./db/elasticsearch/data:/usr/share/elasticsearch/data

logstash:
  image: logstash
  ports:
    - 5141:5141
    - 5141:5141/udp
  volumes:
    - ./logstash.conf:/opt/conf/logstash.conf
  links:
    - elasticsearch:elasticsearch
  command: logstash -f /opt/conf/logstash.conf

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - elasticsearch:elasticsearch

mysql:
  image: mysql
  volumes:
    - ./db/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=sysops
    - MYSQL_ROOT_PASSWORD=root
  ports:
    - 3306:3306

redis:
  image: redis
  ports:
    - 6379:6379
